# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e48d0a0c8a726cd2c1d1c00aea607ebf1c6b013c089edb11160d6e532a2753556d11b2ede42f3c97db23da7b848dfe8f1f52a72d197bf517b48d8c8722a43e7d

test:
  secret_key_base: 008979079e416fa188eb7ec8d339503fbe055f63f5375a980e5ef1057afd90e0c2759fdd0ca7c22bf71df423c28ca4bc03d8c5e94fe522b5f5f71c446be000be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
